title: "AdMU ProgVar Team Notebook"
subtitle: A collection of algorithms, data structures and other useful information for competitive programming. Used by everyone in the Ateneo de Manila University Programming Varsity.
theme: jekyll-theme-cayman
